"""empty message

Revision ID: d8d6d057e67d
Revises: bf1cde70553d
Create Date: 2025-11-25 14:13:44.362963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d6d057e67d'
down_revision = 'bf1cde70553d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vcf_status', sa.Enum('Active', 'Inactive'), server_default='Inactive', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('vcf_status')

    # ### end Alembic commands ###
